openapi: "3.0.0"
info:
  title: Event Logger API
  version: "1.0"
paths:
  /events_stats:
    get:
      summary: Get event statistics
      operationId: app.get_event_stats
      responses:
        200:
          description: A mapping of event codes to their counts
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
